# Generated by Django 4.2.5 on 2023-10-01 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/category/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='uploads/products/%y')),
                ('product_price', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=200)),
                ('product_size', models.CharField(choices=[('Extra Large', 'Extra Large'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=20)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/products/details/%y')),
                ('Product_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allimg', to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='PlacedOreders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('product_price', models.CharField(default=0, max_length=20)),
                ('region', models.CharField(choices=[('Pakistan', 'Pakistan'), ('USA', 'United States'), ('Canada', 'Canada'), ('UAE', 'UAE')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 1, 12, 12, 31, 456293))),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
